service:
  name: /zj_humanoid/robot/set_robot_state/restart
  description: 状态机重启
  type: std_srvs/Trigger
  note: "机器人先进stop软急停状态，再自动变为RUN启动运行，在某些故障状态可以执行，但如果有异常的存在，也可能会失败，将机器人状态机重启 持续检测robot_state话题，经过最长60秒钟的等待，状态应切换为：RUN"
