service:
  name: /zj_humanoid/hand/joint_switch/right
  description: 右手手掌关节运动
  type: zj_humanoid/hand/HandJoint
  demos:
      - right_hand_joint_reset.yaml
      - right_hand_set_gesture_two.yaml
      - right_hand_set_gesture_yeah.yaml
