service:
  name: /zj_humanoid/chassis/agv_charge
  description: 底盘AGV充电控制
  type: chassis_msgs/ChargeControl
  request:
    enable: bool    # true=开启充电，false=关闭充电
  response:
    success: bool
    message: string
  demos:
  note: "WA1、WA2 通用"
